---
title: "data_monthly_v1_0_EDA"
output: "pdf_document"
---

# Load Libraries
```{r, message=FALSE, warning=FALSE}
# Load libraries
library(tidyverse)
library(Hmisc)
library(gridExtra)
library(finalfit)
library(stargazer)
## To load All data sets in the book "Forecasting: principles and practice."
#by Rob J Hyndman and George Athanasopoulos
library(fpp3)
# To create and work with tidy temporal data
library(tsibble)
# To work with date-times and time-spans
library(lubridate)
# Provides a collection of commonly used univariate and multivariate time series models
library(fable )
## To interact directly with the Quandl API and download data
library(Quandl)
# For analyzing tidy time series data.
library(feasts)
# Provides methods and tools for displaying and analyzing univariate time series forecasts library(forecast)
# For estimation, lag selection, diagnostic testing, forecasting, and impulse response functions of VAR library(vars)
#provides tools for statistical calculations
library(stats)
# To assist the quantitative trader in the development,
#testing and deployment of statistically based trading models.
library(quantmod)
# For statistical analysis
library(car)
## To retrieve and display the information returned online by Google Trends
library(gtrendsR)
# To do time series analysis and computational finance.
library(tseries)
```

# Import data from csv file
Rows: 19015
Columns: 62
```{r, message=FALSE, warning=FALSE}
# EDA/src/
raw_df <- read_csv("../../../data/datasets/data_monthly_v1_0.csv")
glimpse(raw_df)
```
# Original dataset
```{r}
raw_df %>% 
  group_by(dataset) %>%
  summarise(count=n())
```
Sites are linked to dataset
```{r}
raw_df %>% 
  group_by(SITE_ID, dataset) %>%
  summarise(count=n())
```




# Convert dataset to TS
## TS month
```{r}
IGBP_month_df <- raw_df %>% 
  group_by(SITE_IGBP, month) %>%
  summarise(TA_F_avg = mean(TA_F, na.rm = T),VPD_F_avg = mean(VPD_F, na.rm = T),
            P_F_avg = mean(P_F, na.rm = T),NETRAD_avg = mean(NETRAD, na.rm = T),
            NEE_VUT_REF_avg = mean(NEE_VUT_REF, na.rm = T),
            NEE_VUT_REF_QC_avg = mean(NEE_VUT_REF_QC, na.rm = T),
            NEE_CUT_REF_avg = mean(NEE_CUT_REF, na.rm = T),
            NEE_CUT_REF_QC_avg = mean(NEE_CUT_REF_QC, na.rm = T),
            GPP_NT_VUT_REF_avg = mean(GPP_NT_VUT_REF, na.rm = T),
            GPP_DT_VUT_REF_avg = mean(GPP_DT_VUT_REF, na.rm = T),
            GPP_NT_CUT_REF_avg = mean(GPP_NT_CUT_REF, na.rm = T),
            GPP_DT_CUT_REF_avg = mean(GPP_DT_CUT_REF, na.rm = T),
            RECO_NT_VUT_REF_avg = mean(RECO_NT_VUT_REF, na.rm = T),
            RECO_DT_VUT_REF_avg = mean(RECO_DT_VUT_REF, na.rm = T),
            RECO_NT_CUT_REF_avg = mean(RECO_NT_CUT_REF, na.rm = T),
            RECO_DT_CUT_REF_avg = mean(RECO_DT_CUT_REF, na.rm = T),
            ET_avg = mean(ET, na.rm = T),
            `BESS-PAR_avg` = mean(`BESS-PAR`, na.rm = T),
            `BESS-PARdiff_avg` = mean(`BESS-PARdiff`, na.rm = T),
            `BESS-RSDN_avg` = mean(`BESS-RSDN`, na.rm = T),
            `CSIF-SIFdaily_avg` = mean(`CSIF-SIFdaily`, na.rm = T),
            `CSIF-SIFinst_avg` = mean(`CSIF-SIFinst`, na.rm = T),
            PET_avg = mean(PET, na.rm = T),Ts_avg = mean(Ts, na.rm = T),
            Tmean_avg = mean(Tmean, na.rm = T),
            prcp_avg = mean(prcp, na.rm = T),
            vpd_avg = mean(vpd, na.rm = T),
            `prcp-lag3_avg` = mean(`prcp-lag3`, na.rm = T),
            `ESACCI-sm_avg` = mean(`ESACCI-sm`, na.rm = T),
            b1_avg = mean(b1, na.rm = T),b2_avg = mean(b2, na.rm = T),
            b3_avg = mean(b3, na.rm = T),b4_avg = mean(b4, na.rm = T),
            b5_avg = mean(b5, na.rm = T),b6_avg = mean(b6, na.rm = T),
            b7_avg = mean(b7, na.rm = T),EVI_avg = mean(EVI, na.rm = T),
            GCI_avg = mean(GCI, na.rm = T),NDVI_avg = mean(NDVI, na.rm = T),
            NDWI_avg = mean(NDWI, na.rm = T),NIRv_avg = mean(NIRv, na.rm = T),
            kNDVI_avg = mean(kNDVI, na.rm = T),
            Percent_Snow_avg = mean(Percent_Snow, na.rm = T),
            Fpar_avg = mean(Fpar, na.rm = T),Lai_avg = mean(Lai, na.rm = T),
            LST_Day_avg = mean(LST_Day, na.rm = T),
            LST_Night_avg = mean(LST_Night, na.rm = T),
            CO2_concentration_avg = mean(CO2_concentration, na.rm = T)
                        )

# raw_df_ts_month <- raw_df %>% as_tsibble(index=month)
IGBP_month_df
```



[link to the handmade codebook]("https://docs.google.com/spreadsheets/d/1-FQsF_sxnA6iBMNpHmGovkj9Xev6BCYg2j3PojNGgyk/edit?usp=sharing")

--- 
# Distribution of Land-cover Type by Site
`SITE_IGBP`(Land-cover Type): 11
`SITE_ID`(Sites): 243
```{r}
raw_df %>% 
  count(SITE_ID)
```

```{r, fig.width=10, fig.height=3}
site_igbp_distribution <-raw_df %>% 
  select(SITE_ID,SITE_IGBP) %>%
  group_by(SITE_IGBP) %>%
  summarise(count= n())

fig1 <- raw_df %>% 
  select(SITE_ID,SITE_IGBP) %>%
  unique() %>%
  group_by(SITE_IGBP) %>%
  summarise(count=n()) %>%
  ggplot(aes(x=SITE_IGBP, y=count)) +
  geom_bar(stat='identity') +
  labs(title = "Distribution of land-cover type(sites)")

fig2 <- site_igbp_distribution %>% 
  ggplot(aes(x=SITE_IGBP, y=count)) +
  geom_bar(stat='identity') +
  labs(title = "Distribution of land-cover type(observations)")

grid.arrange(fig1, fig2, nrow = 1, ncol = 2)
```
```{r}
site_igbp_distribution
```
# Monthly transition of GPP and NEE by land-cover type

```{r}

```


# Summary statistics of variables
Rows: 19015
Columns: 62

```{r}
describe(raw_df)
```











