attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  IGBP:
    '2': 1
    '5': 2
    nan: 0
  day:
    '0': 1
    '1': 2
    '10': 3
    '11': 4
    '12': 5
    '2': 6
    '3': 7
    '4': 8
    '5': 9
    '6': 10
    '7': 11
    '8': 12
    '9': 13
    nan: 0
  hour:
    '0': 0
    '1': 1
    '10': 2
    '11': 3
    '12': 4
    '13': 5
    '14': 6
    '15': 7
    '16': 8
    '17': 9
    '18': 10
    '19': 11
    '2': 12
    '20': 13
    '21': 14
    '22': 15
    '23': 16
    '3': 17
    '4': 18
    '5': 19
    '6': 20
    '7': 21
    '8': 22
    '9': 23
  koppen_main:
    '1': 1
    '2': 2
    nan: 0
  koppen_sub:
    '3': 1
    '5': 2
    nan: 0
  month:
    '0': 1
    nan: 0
  year:
    '0': 1
    nan: 0
embedding_paddings:
- IGBP
- koppen_main
- koppen_sub
- year
- month
- day
embedding_sizes:
  IGBP: !!python/tuple
  - 3
  - 3
  day: !!python/tuple
  - 14
  - 7
  hour: !!python/tuple
  - 24
  - 9
  koppen_main: !!python/tuple
  - 3
  - 3
  koppen_sub: !!python/tuple
  - 3
  - 3
  month: !!python/tuple
  - 2
  - 1
  year: !!python/tuple
  - 2
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: null
logging_metrics: !!python/object:torch.nn.modules.container.ModuleList
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - '0'
      - !!python/object/new:pytorch_forecasting.metrics.point.MAE
        args:
        - MAE()
        state:
          _backward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _buffers: !!python/object/apply:collections.OrderedDict
          - []
          _cache: null
          _computed: null
          _defaults:
            lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
            - !!python/object/apply:torch.storage._load_from_bytes
              - !!binary |
                gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
                ZQpxAVgJAAAAMTkxMDk5MjQ4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgJAAAAMTkxMDk5MjQ4
                cQFhLgEAAAAAAAAAAAAAAAAAAAA=
            - 0
            - !!python/tuple []
            - !!python/tuple []
            - false
            - !!python/object/apply:collections.OrderedDict
              - []
            losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
            - !!python/object/apply:torch.storage._load_from_bytes
              - !!binary |
                gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                Z2UKcQFYCQAAADE5MTA5OTE1MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADE5MTA5OTE1
                MnEBYS4BAAAAAAAAAAAAAAA=
            - 0
            - !!python/tuple []
            - !!python/tuple []
            - false
            - !!python/object/apply:collections.OrderedDict
              - []
          _device: !!python/object/apply:torch.device
          - cpu
          _enable_grad: false
          _forward_cache: null
          _forward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _is_full_backward_hook: null
          _is_synced: false
          _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _modules: !!python/object/apply:collections.OrderedDict
          - []
          _non_persistent_buffers_set: !!set {}
          _parameters: !!python/object/apply:collections.OrderedDict
          - []
          _persistent:
            lengths: false
            losses: false
          _reductions:
            lengths: &id001 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
            losses: *id001
          _should_unsync: true
          _state_dict_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _to_sync: true
          _update_count: 0
          compute_on_cpu: false
          dist_sync_fn: null
          dist_sync_on_step: false
          distributed_available_fn: &id002 !!python/name:torchmetrics.metric.jit_distributed_available ''
          lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
              ZQpxAVgKAAAAMTg4NzczNzE4NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADE4ODc3Mzcx
              ODRxAWEuAQAAAAAAAAAAAAAAAAAAAA==
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
          losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYCgAAADE4ODc3MzQyNTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxODg3NzM0
              MjU2cQFhLgEAAAAAAAAAAAAAAA==
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
          name: MAE
          process_group: null
          quantiles: null
          reduction: mean
          sync_on_compute: true
          training: true
    - - '1'
      - !!python/object/new:pytorch_forecasting.metrics.point.RMSE
        args:
        - RMSE()
        state:
          _backward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _buffers: !!python/object/apply:collections.OrderedDict
          - []
          _cache: null
          _computed: null
          _defaults:
            lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
            - !!python/object/apply:torch.storage._load_from_bytes
              - !!binary |
                gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
                ZQpxAVgKAAAAMTg4NzczODIyNHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADE4ODc3Mzgy
                MjRxAWEuAQAAAAAAAAAAAAAAAAAAAA==
            - 0
            - !!python/tuple []
            - !!python/tuple []
            - false
            - !!python/object/apply:collections.OrderedDict
              - []
            losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
            - !!python/object/apply:torch.storage._load_from_bytes
              - !!binary |
                gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                Z2UKcQFYCgAAADE4ODc3Mzc3NzZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxODg3NzM3
                Nzc2cQFhLgEAAAAAAAAAAAAAAA==
            - 0
            - !!python/tuple []
            - !!python/tuple []
            - false
            - !!python/object/apply:collections.OrderedDict
              - []
          _device: !!python/object/apply:torch.device
          - cpu
          _enable_grad: false
          _forward_cache: null
          _forward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _is_full_backward_hook: null
          _is_synced: false
          _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _modules: !!python/object/apply:collections.OrderedDict
          - []
          _non_persistent_buffers_set: !!set {}
          _parameters: !!python/object/apply:collections.OrderedDict
          - []
          _persistent:
            lengths: false
            losses: false
          _reductions:
            lengths: *id001
            losses: *id001
          _should_unsync: true
          _state_dict_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _to_sync: true
          _update_count: 0
          compute_on_cpu: false
          dist_sync_fn: null
          dist_sync_on_step: false
          distributed_available_fn: *id002
          lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
              ZQpxAVgKAAAAMTg4NzczNzUzNnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADE4ODc3Mzc1
              MzZxAWEuAQAAAAAAAAAAAAAAAAAAAA==
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
          losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYCgAAADE4ODc3MzY3ODRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxODg3NzM2
              Nzg0cQFhLgEAAAAAAAAAAAAAAA==
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
          name: RMSE
          process_group: null
          quantiles: null
          reduction: sqrt-mean
          sync_on_compute: true
          training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
loss: !!python/object/new:pytorch_forecasting.metrics.quantile.QuantileLoss
  args:
  - QuantileLoss(quantiles=[0.02, 0.1, 0.25, 0.5, 0.75, 0.9, 0.98])
  state:
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgJAAAAMTkxMTMzMDU2cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgJAAAAMTkxMTMzMDU2
          cQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCQAAADIwNjE5MTQ1NnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADIwNjE5MTQ1
          NnEBYS4BAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      lengths: false
      losses: false
    _reductions:
      lengths: *id001
      losses: *id001
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 0
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    distributed_available_fn: *id002
    lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgJAAAAMTkxMDk4NzY4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgJAAAAMTkxMDk4NzY4
        cQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCQAAADE5MTEzMzM2MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADE5MTEzMzM2
        MHEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    name: QuantileLoss
    process_group: null
    quantiles:
    - 0.02
    - 0.1
    - 0.25
    - 0.5
    - 0.75
    - 0.9
    - 0.98
    reduction: mean
    sync_on_compute: true
    training: true
lstm_layers: 1
max_encoder_length: 168
monotone_constaints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.TorchNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id003 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple []
    - &id004 !!python/object/apply:numpy.dtype
      args:
      - f4
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      AAAAAA==
  method: identity
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id003
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple []
    - *id004
    - false
    - !!binary |
      AACAPw==
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- IGBP
- koppen_main
- koppen_sub
static_reals: []
time_varying_categoricals_decoder:
- year
- month
- day
- hour
time_varying_categoricals_encoder:
- year
- month
- day
- hour
time_varying_reals_decoder:
- timestep_idx_local
- TA_ERA
- SW_IN_ERA
- LW_IN_ERA
- VPD_ERA
- P_ERA
- PA_ERA
- EVI
- NDVI
- NIRv
- b1
- b2
- b3
- b4
- b5
- b6
- b7
- relative_time_idx
time_varying_reals_encoder:
- timestep_idx_local
- TA_ERA
- SW_IN_ERA
- LW_IN_ERA
- VPD_ERA
- P_ERA
- PA_ERA
- EVI
- NDVI
- NIRv
- b1
- b2
- b3
- b4
- b5
- b6
- b7
- relative_time_idx
- GPP_NT_VUT_REF
- gap_flag_hour
weight_decay: 0.0
x_categoricals:
- IGBP
- koppen_main
- koppen_sub
- year
- month
- day
- hour
x_reals:
- timestep_idx_local
- TA_ERA
- SW_IN_ERA
- LW_IN_ERA
- VPD_ERA
- P_ERA
- PA_ERA
- EVI
- NDVI
- NIRv
- b1
- b2
- b3
- b4
- b5
- b6
- b7
- relative_time_idx
- GPP_NT_VUT_REF
- gap_flag_hour
